volumes:
  n8n_data:
  postgres_data:

services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=shop_user
      - POSTGRES_PASSWORD=shop_password
      - POSTGRES_DB=shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Macht die DB lokal auf Port 5432 erreichbar

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678" # Das Web-Interface von n8n (localhost:5678)
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - TZ=Europe/Berlin
      - N8N_SECURE_COOKIE=false # Deaktiviert Secure-Cookie für lokale Entwicklung
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres